apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: mysh360-cert
  namespace: default
spec:
  secretName: mysh360-cert-tls
  issuerRef:
    name: letsencrypt-staging
  commonName: example.com
  dnsNames:
  - www.example.com
  acme:
    config:
    - http01:
        ingress: sh360-ingress
      domains:
      - www.example.com